### ISSUE TITLE
problem about the number of descriptor 

### ISSUE THREAD

**Issue by BertonYang18** [TingLi2016/DeepDILI#1]
First, thanks for opening your code.
Then, reading your paper, I learn that you have remove the descriptors from 777 to 338. But I just find the file 'QSAR_year_338_pearson_0.9.csv' while the number of descriptor is 777 in it. 
So I want to know whether there is a file which includes 338 descriptors or that is not opening.

**Comment by TingLi2016** [comment]
The 'QSAR_year_338_pearson_0.9.csv'  include 338 descriptors, not 777 descriptors.
